# Set up application configuration constants for the current
# environment.

development:
  google_analytics_code: google_tracking_code

test:
  google_analytics_code: google_tracking_code

cucumber:
  google_analytics_code: google_tracking_code
